-- Migration: Add site manager columns to SITES + create NOTIFICATIONS audit table
-- Schema: DATAOPS_DEV.COLLECTION_FEEDBACK
-- Run in: Snowflake worksheet or SnowSQL as SYSADMIN (needs DDL rights)
-- Do NOT run automatically - Claire runs migrations manually

USE SCHEMA DATAOPS_DEV.COLLECTION_FEEDBACK;

-- Step 1: Add site manager columns to SITES
ALTER TABLE DATAOPS_DEV.COLLECTION_FEEDBACK.SITES
  ADD COLUMN SITE_MANAGER_NAME  VARCHAR(255),
  ADD COLUMN SITE_MANAGER_EMAIL VARCHAR(255);

-- Step 2: Populate Nottingham from the master site list
UPDATE DATAOPS_DEV.COLLECTION_FEEDBACK.SITES s
SET    SITE_MANAGER_NAME  = m.POCMANAGER,
       SITE_MANAGER_EMAIL = m.POCEMAIL
FROM   MD_PROD.REFERENCE.MASTERSITELIST m
WHERE  m.SITENAME  = 'Nottingham'
  AND  s.SITE_NAME = 'Nottingham';

-- Step 3: Create NOTIFICATIONS table for email audit log
-- NOTIFICATION_TYPE values now: LOW_SCORE_ALERT
-- Future: MARKETING_CASE_STUDY, MARKETING_REVIEW
-- STATUS values: SENT, FAILED
CREATE TABLE DATAOPS_DEV.COLLECTION_FEEDBACK.NOTIFICATIONS (
  NOTIFICATION_ID    VARCHAR(36)    DEFAULT UUID_STRING(),
  NOTIFICATION_TYPE  VARCHAR(50)    NOT NULL,
  SESSION_ID         VARCHAR(36),
  RECIPIENT_EMAIL    VARCHAR(255)   NOT NULL,
  SUBJECT            VARCHAR(500),
  STATUS             VARCHAR(20)    NOT NULL,
  ERROR_MESSAGE      VARCHAR(2000),
  RESEND_MESSAGE_ID  VARCHAR(100),
  CREATED_AT         TIMESTAMP_LTZ  DEFAULT CURRENT_TIMESTAMP()
);

-- Step 4: Verification
-- New columns exist on SITES
SELECT SITE_ID, SITE_NAME, SITE_MANAGER_NAME, SITE_MANAGER_EMAIL
FROM   DATAOPS_DEV.COLLECTION_FEEDBACK.SITES;

-- Nottingham row is populated
SELECT SITE_NAME, SITE_MANAGER_NAME, SITE_MANAGER_EMAIL
FROM   DATAOPS_DEV.COLLECTION_FEEDBACK.SITES
WHERE  SITE_NAME = 'Nottingham';

-- NOTIFICATIONS table is queryable
SELECT COUNT(*) AS ROW_COUNT FROM DATAOPS_DEV.COLLECTION_FEEDBACK.NOTIFICATIONS;
